### ISSUE TITLE
Carcel

### ISSUE THREAD

**Issue by olifer97** [nildius/TP2Java#1]
Como manejar el tema de la carcel con los turnos y pagar la fianza.

**Comment by olifer97** [comment]
No me cierra que primero el jugador entra a la carcel y despues con pisar() pasan los turnos, para mi deberia ir en pisar siempre o no, pisar deberia ser cuando entra a la carcel y despues si no puede moverse se resta un turno pero no hay otra funcion para eso

**Comment by k3v1nnnn** [comment]
como andas, mira yo lo pense asi : pisar es cuando ya esta sobre la casilla de carcel, es ahi donde se restan los turnos, y el metodo cayo en la carcel va ser usado por la policia que te manda a la carcel, hasta ese momento todavia no estas sobre la casilla carcel, y descontar mientras no estas sobre la casilla me parece erroneo

**Comment by olifer97** [comment]
Claro cuando caes en la policia y te manda a la carcel tiene sentido. Pero tambien esta ek caso que caes directo en ka carcel y te quedas ahi.

**Comment by k3v1nnnn** [comment]
changos!!!, bueno es momento de refactorizar 💯 , pero si llega a la carcel sin que lo mande la policia, se que da encarcelado igual o no tiene ningun efecto???, en el enunciado no lo aclara.

**Comment by olifer97** [comment]
Tenia entendido que si. Igual me gusta mas la idea que el pisar() de la policia llame a la funcion q te manda a la carcel o algo asi.

**Comment by k3v1nnnn** [comment]
bueno segun las reglas del monopoly si llegas a carcel sin que te mande la policia no pasa nada, recomiendo altamente que esto sea asi aca, o lo podemos consultar al ayudante. si este fuera el caso tenemos que refactorizar, tenemos que verificar de que casillero vino el jugador.

**Comment by olifer97** [comment]
Cárcel: un jugador al caer en este casillero debe esperar 3 turnos para salir. Es decir, recién cuando le toque por 4ta vez podrá moverse. Salvo que cuando cuando ya haya pasado 1 turno de la cárcel (o sea en el turno 2 y 3 de espera) pague una fianza de $45000.

Esto dice el enunciado.

**Comment by lucaslois** [comment]
Si un jugador cae en la cárcel se lo considera preso. La consigna lo aclara (y difiere a las reglas originales del Monopoly).

Para mi el pisar debe ejecutarse una vez en cada uno. Uno en carcel y uno en Policia (con sus respectivos comportamientos) y que el descuento se haga luego con un controlador de turnos. Me parece inválido llamar al método Pisar() cuando el jugador no ejecutó ningún movimiento, ya que por cómo venimos implementando, el Pisar se ejecuta cuando un jugador cae en una casilla nueva.
